# render.yaml
services:
  - type: web
    name: spring-backend
    env: java
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
